model_name_or_path: ./models/monetgpt
template: qwen2_vl
infer_backend: huggingface  # choices: [huggingface, vllm]
trust_remote_code: true
pure_bf16: true
trust_remote_code: true
max_new_tokens: 6000
skip_special_tokens: false
